[book]
title = "Aprendiendo Zig"
description = "Learning Zig by Karl Seguin"
authors = [""]
language = "es-AR"
multilingual = false
src = "."

[output.html]
git-repository-url = "https://github.com/marcusbrunello/learning-zig"
edit-url-template = "https://github.com/marcusbrunello/learning-zig/edit/main/{path}"
additional-js = ["static/zig-hl.js"]
additional-css = ["static/last-changed.css"]
site-url = "/learning-zig/"

[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter

[output.html.search]
enable = true

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]